- name: Deploy website container
  hosts: web
  become: yes

  tasks:

    - name: create site folder
      file:
        path: /home/ubuntu/site
        state: directory

    - name: copy website
      copy:
        src: ../website/
        dest: /home/ubuntu/site/

    - name: copy nginx config
      copy:
        src: ../docker/nginx.conf
        dest: /home/ubuntu/nginx.conf

    - name: stop old container
      shell: docker rm -f resume-site || true

    - name: run nginx with ssl
      shell: |
        docker run -d \
        --name resume-site \
        -p 80:80 \
        -p 443:443 \
        -v /home/ubuntu/site:/usr/share/nginx/html \
        -v /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf \
        -v /home/ubuntu/ssl:/ssl \
        nginx